### ISSUE TITLE
Error during instalation

### ISSUE THREAD

**Issue by victor-ahuir** [a-castellano/Toggl-Wrapper#24]
When I try to install this module at OSX 10.11.6 the compilation crashes
1.
`perl Makefile.PL`
Output:

>Checking if your kit is complete...
Warning: the following files are missing in your kit:
	README
Please inform the author.
WARNING: Setting ABSTRACT via file 'lib/Toggl/Wrapper.pm' failed
 at /System/Library/Perl/5.18/ExtUtils/MakeMaker.pm line 611.
Writing Makefile for Toggl::Wrapper
Writing MYMETA.yml and MYMETA.json

2.
`make`
Output:
>make
cp README.pod blib/lib/Toggl/README.pod
cp lib/Utils/Common.pm blib/lib/Utils/Common.pm
cp lib/Toggl/Wrapper.pm blib/lib/Toggl/Wrapper.pm
cp lib/Utils/Role/Serializable/JSON.pm blib/lib/Utils/Role/Serializable/JSON.pm
cp lib/Toggl/Wrapper/TimeEntry.pm blib/lib/Toggl/Wrapper/TimeEntry.pm
Manifying blib/man3/Toggl::Wrapper::TimeEntry.3pm
Manifying blib/man3/Toggl::README.3pm
Manifying blib/man3/Utils::Common.3pm
Manifying blib/man3/Toggl::Wrapper.3pm
3.
`make test`
Output:

> make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ........ 1/? Bailout called.  Further testing stopped:
Failed test 'use Toggl::Wrapper;'
   at t/00-load.t line 9.
     Tried to use 'Toggl::Wrapper'.
     Error:  **Can't locate MooseX/Types/Email.pm in @INC (* you may need to install the MooseX::Types::Email module) (@INC containsToggl-Wrapper/blib/lib xToggl-Wrapper/blib/arch /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18) at Toggl-Wrapper/blib/lib/Toggl/Wrapper.pm line 18.
 BEGIN failed--compilation aborted at Toggl-Wrapper/blib/lib/Toggl/Wrapper.pm line 18.
 Compilation failed in require at (eval 4) line 2.
 BEGIN failed--compilation aborted at (eval 4) line 2.
Use of uninitialized value $Toggl::Wrapper::VERSION in concatenation (.) or string at t/00-load.t line 13.
 Testing Toggl::Wrapper , Perl 5.018002, /usr/bin/perl
 Looks like you failed 1 test of 1.
FAILED--Further testing stopped.
make: *** [test_dynamic] Error 1
`

**Comment by a-castellano** [comment]
Dear  vicdoz,

I should specify in Readme file how to manage or install this project dependencies 

Please, try to run `cpanm --quiet --installdeps --notest .` inside project root.

Please let me know if it works and if you need something more form me.

Cheers

**Comment by a-castellano** [comment]
Hi again @vicdoz 

I have just updated Readme.pod, pelase check ir as soon as you can.

Cheers.

**Comment by victor-ahuir** [comment]
Yeah, after install dependencies the life is pink.
Now works.
Thanks!
